name: learn_alphabet

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.6.3
  speech_to_text: ^6.6.1
  audioplayers: ^6.1.0 # Stable version of audioplayers
  cupertino_icons: ^1.0.2 # Default icons for iOS
  voice_assistant: ^1.0.1
  permission_handler: ^11.1.0
  google_fonts: ^6.2.1
  video_player: ^2.9.2
  video_player_android: ^2.3.3
  animate_do: ^3.3.9
  confetti: ^0.8.0
  shared_preferences: ^2.5.2
  wave: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/alphabet.png"

flutter:
  uses-material-design: true
  assets:
    - assets/background1.jpg
    - assets/bg_music.mp3
    - assets/mute.png
    - assets/unmute.png
    - assets/alphabet.png
    - assets/logo.mp4
    - assets/word_puzzle/success.mp3
    - assets/word_puzzle/drop.mp3
    - assets/word_puzzle/correct.mp3
    - assets/word_puzzle/drop.mp3
    - assets/backgroundimage.jpg
    - assets/alphabets/a.png
    - assets/alphabets/b.png
    - assets/alphabets/c.png
    - assets/alphabets/d.png
    - assets/alphabets/e.png
    - assets/alphabets/f.png
    - assets/alphabets/g.png
    - assets/alphabets/h.png
    - assets/alphabets/i.png
    - assets/alphabets/j.png
    - assets/alphabets/k.png
    - assets/alphabets/l.png
    - assets/alphabets/m.png
    - assets/alphabets/n.png
    - assets/alphabets/o.png
    - assets/alphabets/p.png
    - assets/alphabets/q.png
    - assets/alphabets/r.png
    - assets/alphabets/s.png
    - assets/alphabets/t.png
    - assets/alphabets/u.png
    - assets/alphabets/v.png
    - assets/alphabets/w.png
    - assets/alphabets/x.png
    - assets/alphabets/y.png
    - assets/alphabets/z.png
    - assets/home-screen/abc.png
    - assets/home-screen/matching.png
    - assets/home-screen/voice.png
    - assets/home-screen/puzzle.png
    - assets/home-screen/stories.png
    - assets/board.png
    - assets/alphabet-sounds/
    - assets/alphabet-sounds/wrong.mp3
    - assets/alphabet-sounds/correct.mp3
    - assets/alphabet-sounds/tap.mp3
    - assets/all-letters/
    - assets/cpsu-logo.png
    - assets/client-logo.png
    - assets/stories/ben_ted.jpg
    - assets/stories/the_zoo.jpg
    - assets/stories/trophy.gif
    - assets/stories/tryagain.gif
    - assets/stories/sound/gameover.mp3
    - assets/stories/sound/win.mp3
    - assets/btn_home.png

