name: learn_alphabet

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.6.3
  speech_to_text: ^5.5.3
  audioplayers: ^6.1.0 # Stable version of audioplayers
  cupertino_icons: ^1.0.2 # Default icons for iOS

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/alphabet.png"

flutter:
  uses-material-design: true
  assets:
    - assets/background1.jpg
    - assets/alphabet.png
    - assets/backgroundimage.jpg
    - assets/alphabets/a.png
    - assets/alphabets/b.png
    - assets/alphabets/c.png
    - assets/alphabets/d.png
    - assets/alphabets/e.png
    - assets/alphabets/f.png
    - assets/alphabets/g.png
    - assets/alphabets/h.png
    - assets/alphabets/i.png
    - assets/alphabets/j.png
    - assets/alphabets/k.png
    - assets/alphabets/l.png
    - assets/alphabets/m.png
    - assets/alphabets/n.png
    - assets/alphabets/o.png
    - assets/alphabets/p.png
    - assets/alphabets/q.png
    - assets/alphabets/r.png
    - assets/alphabets/s.png
    - assets/alphabets/t.png
    - assets/alphabets/u.png
    - assets/alphabets/v.png
    - assets/alphabets/w.png
    - assets/alphabets/x.png
    - assets/alphabets/y.png
    - assets/alphabets/z.png
    - assets/home-screen/abc.png
    - assets/home-screen/matching.png
    - assets/alphabet-sounds/
    - assets/alphabet-sounds/wrong.mp3
    - assets/alphabet-sounds/correct.mp3
    - assets/matching-letters/

dependency_overrides:
  speech_to_text:
    git:
      url: https://github.com/csdcorp/speech_to_text.git
      path: speech_to_text
