final Map<String, String> correctRhymingWords = {
  'hot': 'pot',
  'cat': 'bat',
  'sun': 'fun',
  'pen': 'ten',
  'win': 'bin',
  'dog': 'fog',
  'cap': 'map',
  'hop': 'mop',
  'red': 'bed',
  'zip': 'tip',
  'tree': 'free',
  'car': 'star',
  'bee': 'see',
  'rain': 'train',
  'boat': 'coat',
  'fish': 'dish',
  'hat': 'rat',
  'light': 'night',
  'king': 'ring',
  'book': 'look',
};

final Map<String, List<String>> wrongChoices = {
  'hot': ['boy', 'big', 'top'],
  'cat': ['dog', 'sun', 'car'],
  'sun': ['pen', 'dog', 'bag'],
  'pen': ['cap', 'dog', 'sun'],
  'win': ['dog', 'hot', 'cap'],
  'dog': ['pen', 'cat', 'sun'],
  'cap': ['pen', 'win', 'dog'],
  'hop': ['cap', 'pen', 'sun'],
  'red': ['boy', 'cat', 'bat'],
  'zip': ['dog', 'sun', 'pen'],
  'tree': ['car', 'pen', 'dog'],
  'car': ['dog', 'sun', 'bag'],
  'bee': ['dog', 'hot', 'cap'],
  'rain': ['pen', 'cat', 'sun'],
  'boat': ['pen', 'win', 'dog'],
  'fish': ['cap', 'pen', 'sun'],
  'hat': ['boy', 'cat', 'bat'],
  'light': ['dog', 'sun', 'pen'],
  'king': ['pen', 'dog', 'sun'],
  'book': ['dog', 'sun', 'pen'],
};
