final Map<String, String> correctRhymingWordsEasy = {
  'hot': 'pot',
  'cat': 'bat',
  'sun': 'fun',
  'pen': 'ten',
  'win': 'bin',
  'dog': 'fog',
  'cap': 'map',
  'hop': 'mop',
  'red': 'bed',
  'zip': 'tip',
  'tree': 'free',
  'car': 'star',
  'bee': 'see',
  'rain': 'train',
  'boat': 'coat',
  'fish': 'dish',
  'hat': 'rat',
  'light': 'night',
  'king': 'ring',
  'book': 'look',
  // Added Words
  'ball': 'hall',
  'clock': 'rock',
  'chair': 'bear',
  'bell': 'shell',
  'hand': 'sand',
  'frog': 'log',
  'bird': 'third',
  'key': 'they',
  'moon': 'spoon',
  'duck': 'truck',
  'plane': 'train',
  'rose': 'nose',
  'milk': 'silk',
  'star': 'jar',
  'glass': 'class',
};

final Map<String, List<String>> wrongChoicesEasy = {
  'hot': ['boy', 'big', 'top'],
  'cat': ['dog', 'sun', 'car'],
  'sun': ['pen', 'bat', 'bag'],
  'pen': ['cap', 'dog', 'map'],
  'win': ['dog', 'sun', 'cap'],
  'dog': ['pen', 'cat', 'sun'],
  'cap': ['pen', 'hot', 'hop'],
  'hop': ['keep', 'bed', 'hat'],
  'red': ['boy', 'car', 'top'],
  'zip': ['dog', 'star', 'pen'],
  'tree': ['car', 'dog', 'bag'],
  'car': ['dog', 'sun', 'book'],
  'bee': ['dog', 'cap', 'win'],
  'rain': ['pen', 'cat', 'book'],
  'boat': ['pen', 'win', 'key'],
  'fish': ['cap', 'pen', 'sun'],
  'hat': ['boy', 'cat', 'moon'],
  'light': ['dog', 'pen', 'car'],
  'king': ['pen', 'dog', 'sun'],
  'book': ['dog', 'car', 'cap'],
  // Added Wrong Choices
  'ball': ['dog', 'hat', 'way'],
  'clock': ['key', 'cup', 'click'],
  'chair': ['frog', 'boar', 'lamp'],
  'bell': ['kite', 'tea', 'cat'],
  'hand': ['cap', 'sell', 'bag'],
  'frog': ['star', 'dig', 'bat'],
  'bird': ['hat', 'chair', 'ball'],
  'key': ['kite', 'car', 'cap'],
  'moon': ['pen', 'spy', 'bag'],
  'duck': ['tree', 'toy', 'fish'],
  'plane': ['glass', 'star', 'top'],
  'rose': ['bell', 'cap', 'sun'],
  'milk': ['frog', 'top', 'ball'],
  'star': ['sky', 'cap', 'ban'],
  'glass': ['school', 'bird', 'pen'],
};
