final Map<String, String> correctRhymingWordsHard = {
  'banana': 'bandana',
  'chocolate': 'elaborate',
  'tomorrow': 'sorrow',
  'cucumber': 'number',
  'elephant': 'relevant',
  'carousel': 'parallel',
  'umbrella': 'Mozzarella',
  'volcano': 'piano',
  'triangle': 'rectangle',
  'adventure': 'departure',
  'cylinder': 'remainder',
  'domino': 'torpedo',
  'disaster': 'plaster',
  'envelope': 'telescope',
  'furniture': 'miniature',
  // Added Words
  'president': 'resident',
  'chameleon': 'pavilion',
  'celebrate': 'decorate',
  'beautiful': 'wonderful',
  'marathon': 'pentagon',
  'telephone': 'microphone',
  'avocado': 'tornado',
  'volunteer': 'pioneer',
  'chandelier': 'souvenir',
  'mechanic': 'volcanic',
};

final Map<String, List<String>> wrongChoicesHard = {
  'banana': ['camera', 'elephant', 'parrot'],
  'chocolate': ['sunshine', 'garden', 'candle'],
  'tomorrow': ['morning', 'journey', 'jungle'],
  'cucumber': ['carousel', 'lettuce', 'carpet'],
  'elephant': ['giraffe', 'tiger', 'pencil'],
  'carousel': ['circus', 'airplane', 'telescope'],
  'umbrella': ['raincoat', 'jacket', 'mountain'],
  'volcano': ['island', 'sailboat', 'grapefruit'],
  'triangle': ['circle', 'square', 'elevator'],
  'adventure': ['journey', 'backpack', 'calendar'],
  'cylinder': ['triangle', 'scooter', 'keyboard'],
  'domino': ['buffalo', 'volcano', 'avocado'],
  'disaster': ['failure', 'accident', 'mountain'],
  'envelope': ['package', 'backbone', 'pencil'],
  'furniture': ['closet', 'mirror', 'wallpaper'],
  // Added Wrong Choices
  'president': ['minister', 'hospital', 'computer'],
  'chameleon': ['iguana', 'elephant', 'microphone'],
  'celebrate': ['festival', 'passport', 'umbrella'],
  'beautiful': ['amazing', 'symphony', 'calendar'],
  'marathon': ['polygon', 'barbeque', 'tornado'],
  'telephone': ['telescope', 'satellite', 'pyramid'],
  'avocado': ['mountain', 'parachute', 'hamburger'],
  'volunteer': ['architect', 'alligator', 'magazine'],
  'chandelier': ['souvenir', 'calendar', 'pineapple'],
  'mechanic': ['volcano', 'elephant', 'fantasy'],
};
