final Map<String, String> correctRhymingWordsMedium = {
  'table': 'cable',
  'apple': 'grapple',
  'flower': 'power',
  'river': 'giver',
  'candle': 'handle',
  'planet': 'granite',
  'mother': 'brother',
  'window': 'meadow',
  'bottle': 'throttle',
  'pencil': 'stencil',
  'garden': 'harden',
  'hunger': 'longer',
  'jungle': 'bundle',
  'silver': 'quiver',
  'winter': 'splinter',
  // Added Words
  'pickle': 'tickle',
  'thunder': 'wonder',
  'danger': 'stranger',
  'tiger': 'lighter',
  'rocket': 'pocket',
  'lumber': 'number',
  'dancer': 'cancer',
  'blunder': 'thunder',
};

final Map<String, List<String>> wrongChoicesMedium = {
  'table': ['chair', 'pencil', 'spoon'],
  'apple': ['grape', 'orange', 'melon'],
  'flower': ['tree', 'garden', 'leaf'],
  'river': ['stream', 'lake', 'ocean'],
  'candle': ['lamp', 'torch', 'flame'],
  'planet': ['star', 'moon', 'comet'],
  'mother': ['auntie', 'daddy', 'son'],
  'window': ['door', 'floor', 'wall'],
  'bottle': ['glass', 'cup', 'mug'],
  'pencil': ['eraser', 'pen', 'marker'],
  'garden': ['forest', 'tree', 'yard'],
  'hunger': ['thirst', 'anger', 'pain'],
  'jungle': ['forest', 'desert', 'bush'],
  'silver': ['gold', 'diamond', 'bronze'],
  'winter': ['summer', 'autumn', 'spring'],
  // Added Wrong Choices
  'pickle': ['cucumber', 'pepper', 'carrot'],
  'thunder': ['storm', 'rain', 'lightning'],
  'danger': ['alert', 'hazard', 'fire'],
  'tiger': ['lion', 'cheetah', 'panther'],
  'rocket': ['spaceship', 'satellite', 'planet'],
  'lumber': ['wood', 'tree', 'branch'],
  'dancer': ['singer', 'actor', 'painter'],
  'blunder': ['mistake', 'error', 'failure'],
};
